// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plvcaumlgecpuaawnobi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsdmNhdW1sZ2VjcHVhYXdub2JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTk5MzMsImV4cCI6MjA2MTY5NTkzM30.NYGPzTwjyqBNFqdyWzF3mCDO6ds_eTmX5140-914L6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);